# Generated by Django 4.0.3 on 2022-12-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price_alter_product_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_menu_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Товар меню',
                'verbose_name_plural': 'Товары меню',
            },
        ),
    ]
